// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7Fi3MqMDfOh-HuLTeJIBNqcMzlvKzkUM',
    appId: '1:607625750476:web:91b2a75a26853ece789f69',
    messagingSenderId: '607625750476',
    projectId: 'mfde-ditonton',
    authDomain: 'mfde-ditonton.firebaseapp.com',
    storageBucket: 'mfde-ditonton.appspot.com',
    measurementId: 'G-T0NH5MQ2DM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxXrwlde68bueaG_YafT20F7qCrFMRCBU',
    appId: '1:607625750476:android:3f5bd27281409f1f789f69',
    messagingSenderId: '607625750476',
    projectId: 'mfde-ditonton',
    storageBucket: 'mfde-ditonton.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3LAH-UjBbuija0-7xV1f5X2CPVaPKw-g',
    appId: '1:607625750476:ios:b722f86ce570b873789f69',
    messagingSenderId: '607625750476',
    projectId: 'mfde-ditonton',
    storageBucket: 'mfde-ditonton.appspot.com',
    iosClientId: '607625750476-1svipsv4p83ngalukt90scqhfuc7509n.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
